/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AboutMeService } from "../aboutMe.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AboutMeCreateInput } from "./AboutMeCreateInput";
import { AboutMe } from "./AboutMe";
import { AboutMeFindManyArgs } from "./AboutMeFindManyArgs";
import { AboutMeWhereUniqueInput } from "./AboutMeWhereUniqueInput";
import { AboutMeUpdateInput } from "./AboutMeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AboutMeControllerBase {
  constructor(
    protected readonly service: AboutMeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AboutMe })
  @nestAccessControl.UseRoles({
    resource: "AboutMe",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAboutMe(
    @common.Body() data: AboutMeCreateInput
  ): Promise<AboutMe> {
    return await this.service.createAboutMe({
      data: data,
      select: {
        content: true,
        createdAt: true,
        id: true,
        image: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AboutMe] })
  @ApiNestedQuery(AboutMeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AboutMe",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aboutMes(@common.Req() request: Request): Promise<AboutMe[]> {
    const args = plainToClass(AboutMeFindManyArgs, request.query);
    return this.service.aboutMes({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,
        image: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AboutMe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AboutMe",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aboutMe(
    @common.Param() params: AboutMeWhereUniqueInput
  ): Promise<AboutMe | null> {
    const result = await this.service.aboutMe({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,
        image: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AboutMe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AboutMe",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAboutMe(
    @common.Param() params: AboutMeWhereUniqueInput,
    @common.Body() data: AboutMeUpdateInput
  ): Promise<AboutMe | null> {
    try {
      return await this.service.updateAboutMe({
        where: params,
        data: data,
        select: {
          content: true,
          createdAt: true,
          id: true,
          image: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AboutMe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AboutMe",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAboutMe(
    @common.Param() params: AboutMeWhereUniqueInput
  ): Promise<AboutMe | null> {
    try {
      return await this.service.deleteAboutMe({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,
          image: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
